version: '3'
services:

  insight_kmd:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3001
      - RPCPORT=8232
      - ZMQPPORT=8332
    depends_on:
      - komodod

  insight_kv:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3015
      - RPCPORT=8299
      - ZMQPPORT=9014
    depends_on:
      - komodod

  insight_mgw:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3012
      - RPCPORT=12386
      - ZMQPPORT=9011
    depends_on:
      - komodod

  insight_crypto:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3008
      - RPCPORT=8516
      - ZMQPPORT=9007
    depends_on:
      - komodod

  komodod:
    build:
      ./komodod
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
    volumes:
      - komodod-assetchain:/komodo
    restart: always
volumes:
  komodod-assetchain:

