version: '3'
services:

  insight_kmd:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3001
      - RPCPORT=8232
      - ZMQPPORT=8332
    depends_on:
      - komodod

  insight_pgt:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3030
      - RPCPORT=46705
      - ZMQPPORT=9029
    depends_on:
      - komodod

  insight_oot:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3023
      - RPCPORT=12467
      - ZMQPPORT=9022
    depends_on:
      - komodod

  insight_eql:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3029
      - RPCPORT=10306
      - ZMQPPORT=9028
    depends_on:
      - komodod

  insight_kv:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3015
      - RPCPORT=8299
      - ZMQPPORT=9014
    depends_on:
      - komodod

  insight_mgw:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3012
      - RPCPORT=12386
      - ZMQPPORT=9011
    depends_on:
      - komodod

  insight_bntn:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3024
      - RPCPORT=14358
      - ZMQPPORT=9023
    depends_on:
      - komodod

  insight_crypto:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3008
      - RPCPORT=8516
      - ZMQPPORT=9007
    depends_on:
      - komodod

  insight_ninja:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3022
      - RPCPORT=8427
      - ZMQPPORT=9021
    depends_on:
      - komodod

  insight_bet:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3007
      - RPCPORT=14250
      - ZMQPPORT=9006
    depends_on:
      - komodod

  insight_chain:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3025
      - RPCPORT=15587
      - ZMQPPORT=9024
    depends_on:
      - komodod

  insight_mshark:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3010
      - RPCPORT=8846
      - ZMQPPORT=9009
    depends_on:
      - komodod

  insight_etomic:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3020
      - RPCPORT=10271
      - ZMQPPORT=9019
    depends_on:
      - komodod

  insight_jumblr:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3006
      - RPCPORT=15106
      - ZMQPPORT=9005
    depends_on:
      - komodod

  insight_dsec:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3027
      - RPCPORT=11557
      - ZMQPPORT=9026
    depends_on:
      - komodod

  insight_glxt:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3028
      - RPCPORT=15723
      - ZMQPPORT=9027
    depends_on:
      - komodod

  insight_axo:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3019
      - RPCPORT=12927
      - ZMQPPORT=9018
    depends_on:
      - komodod

  insight_bots:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3011
      - RPCPORT=11964
      - ZMQPPORT=9010
    depends_on:
      - komodod

  insight_mnz:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3018
      - RPCPORT=14337
      - ZMQPPORT=9017
    depends_on:
      - komodod

  insight_ceal:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3016
      - RPCPORT=11116
      - ZMQPPORT=9015
    depends_on:
      - komodod

  insight_btch:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3021
      - RPCPORT=8800
      - ZMQPPORT=9020
    depends_on:
      - komodod

  insight_prlpay:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3026
      - RPCPORT=9679
      - ZMQPPORT=9025
    depends_on:
      - komodod

  insight_supernet:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3003
      - RPCPORT=11341
      - ZMQPPORT=9002
    depends_on:
      - komodod

  insight_pangea:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3005
      - RPCPORT=14068
      - ZMQPPORT=9004
    depends_on:
      - komodod

  insight_hodl:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3009
      - RPCPORT=14431
      - ZMQPPORT=9008
    depends_on:
      - komodod

  insight_dex:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3004
      - RPCPORT=11890
      - ZMQPPORT=9003
    depends_on:
      - komodod

  insight_mesh:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3017
      - RPCPORT=9455
      - ZMQPPORT=9016
    depends_on:
      - komodod

  insight_wlc:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3014
      - RPCPORT=12167
      - ZMQPPORT=9013
    depends_on:
      - komodod

  insight_coqui:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3013
      - RPCPORT=14276
      - ZMQPPORT=9012
    depends_on:
      - komodod

  insight_revs:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3002
      - RPCPORT=10196
      - ZMQPPORT=9001
    depends_on:
      - komodod

  komodod:
    build:
      ./komodod
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
    volumes:
      - komodod-assetchain:/komodo
    restart: always
  nginx:
    build:
      ./nginx
    network_mode: "host"
    environment:
      - DEPLOY_TARGET
    restart: always
volumes:
  komodod-assetchain:

