version: '3'

services:
  insight_kmd:
    build:
      ./insight
    restart: always
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
      - GUIPORT=3001
      - RPCPORT=8232
      - ZMQPPORT=8332
    depends_on:
      - komodod
  komodod:
    build:
      ./komodod
    network_mode: "host"
    environment:
      - RPCUSER
      - RPCPASSWORD
    volumes:
      - komodod-assetchain:/komodo
    restart: always
volumes:
  komodod-assetchain: